# EFS only supports filesystem backup
schedules:
  lr-ta:
    disabled: false
    schedule: "15 2 * * 1-5"
    template:
      csiSnapshotTimeout: 0s
      defaultVolumesToFsBackup: true
      ttl: "720h"
      # excludedNamespaces:
      # - velero
      # - default
      includedNamespaces:
      - dev
      includedResources:
      - "*"
    useOwnerReferencesInBackup: false
