apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /manifest/trio
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app-type: "user"
spec:
  destination:
    namespace: trio
    name: in-cluster
  project: default
  source:
    repoURL: https://github.com/lrochette/ta-autopilot.git
    targetRevision: main
    path: manifests/trio
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
