apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: color
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: demo-dev
            short: dev
          - cluster: demo-qa
            short: qa

  template:
    metadata:
      name: 'color-{{short}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io/foreground
      annotations:
        argocd.argoproj.io/manifest-generate-paths: '.'
        argocd.argoproj.io/sync-wave: "30"
        notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "Laurent Rochette"
      labels:
        app-type: "user"
    spec:
      project: default
      source:
        repoURL: https://github.com/lrochette/ta-autopilot.git
        targetRevision: main
        path: 'manifests/color/{{short}}'
      destination:
        name: 'in-cluster'
        namespace: '{{short}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - PrunePropagationPolicy=foreground
          - Replace=false
          - PruneLast=false
          - Validate=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=false
