apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.aegon.io/argocd-app: gts-cicd-dev
  name: gts-cicd-dev
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
      - name: environment
        value: "dev"
      - name: clusterName
        value: in-cluster
      - name: appName
        value: "gts-cicd"
      - name: awsAccountId
        value: "xxxxxx"
      - name: vpcId
        value: "xxxxxx"
      - name: awsLBController.enabled
        value: "false"
      - name: certManager.enabled
        value: "true"
      - name: cicdDocs.enabled
        value: "false"
      - name: clusterAutoscaler.enabled
        value: "true"
      - name: externalDNS.enabled
        value: "false"
      - name: kubePrometheusStack.enabled
        value: "false"
      - name: metricsServer.enabled
        value: "false"
      - name: nginxIngressController.enabled
        value: "false"
      - name: secretStoreCSIDriver.enabled
        value: "false"
      - name: secretStoreCSIDriverProviderAWS.enabled
        value: "false"
      - name: snapshotController.enabled
        value: "false"
      - name: velero.enabled
        value: "true"
    path: infra
    repoURL: https://github.com/lrochette/ta-autopilot.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
      limit: 5
    syncOptions:
    - CreateNamespace=true
