apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: default-top
  name: argo-rollouts
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argo-rollouts
  project: default
  source:
    chart: argo-rollouts
    helm:
      releaseName: argo-rollouts
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.39.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
