apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: argo-rollouts
    repoURL: https://codefresh-io.github.io/argo-helm
    targetRevision: 2.37.3-1-v1.7.1-CR-24605
    helm:
      releaseName: argo-rollouts
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
